<?php
namespace Tests\Feature;
use App\Models\{Event,User,Venue};use Illuminate\Foundation\Testing\RefreshDatabase;use Tests\TestCase;
class EventWorkflowTest extends TestCase{use RefreshDatabase;protected function setUp():void{parent::setUp();$this->seed();}
 public function test_pic_can_login_and_create_draft():void{$this->postJson('/api/login',['email'=>'pic@technolife.test','password'=>'password'])->assertOk();$this->postJson('/api/events',['event_name'=>'Draft demo','submit'=>false])->assertCreated()->assertJsonPath('status','DRAFT');}
 public function test_invalid_login_fails():void{$this->postJson('/api/login',['email'=>'pic@technolife.test','password'=>'wrong'])->assertStatus(422);}
 public function test_pic_cannot_approve():void{$pic=User::where('role','PIC')->first();$this->actingAs($pic)->postJson('/api/events/1/decision',['decision'=>'APPROVE'])->assertForbidden();}
 public function test_admin_route_is_forbidden_to_pic():void{$this->actingAs(User::where('role','PIC')->first())->getJson('/api/users')->assertForbidden();}
 public function test_boundary_times_do_not_conflict_but_overlap_does():void{$pic=User::where('role','PIC')->first();$venue=Venue::first();Event::create(['created_by'=>$pic->id,'event_name'=>'Existing','event_type'=>'Meeting','event_date'=>today()->addDays(2),'start_time'=>'09:00','end_time'=>'12:00','venue_id'=>$venue->id,'staff_required'=>0,'status'=>'SCHEDULED']);$base=['event_name'=>'Boundary','event_type'=>'Meeting','event_date'=>today()->addDays(2)->format('Y-m-d'),'venue_id'=>$venue->id,'staff_required'=>0,'submit'=>true];$this->actingAs($pic)->postJson('/api/events',$base+['start_time'=>'12:00','end_time'=>'15:00'])->assertCreated();$this->actingAs($pic)->postJson('/api/events',$base+['event_name'=>'Overlap','start_time'=>'11:00','end_time'=>'13:00'])->assertConflict();}
 public function test_approver_can_approve_and_rejection_requires_reason():void{$pic=User::where('role','PIC')->first();$approver=User::where('role','APPROVER')->first();$v=Venue::first();$e=Event::create(['created_by'=>$pic->id,'event_name'=>'Pending','event_type'=>'Meeting','event_date'=>today()->addDays(4),'start_time'=>'09:00','end_time'=>'10:00','venue_id'=>$v->id,'staff_required'=>0,'status'=>'PENDING_APPROVAL']);$this->actingAs($approver)->postJson("/api/events/$e->id/decision",['decision'=>'REJECT'])->assertUnprocessable();$this->actingAs($approver)->postJson("/api/events/$e->id/decision",['decision'=>'APPROVE'])->assertOk()->assertJsonPath('status','SCHEDULED');}
 public function test_calendar_excludes_draft_and_rejected():void{$pic=User::where('role','PIC')->first();$response=$this->actingAs($pic)->getJson('/api/events?calendar=1')->assertOk();foreach($response->json('data') as $e)$this->assertNotContains($e['status'],['DRAFT','REJECTED']);}
 public function test_staff_only_sees_assigned_events():void{$staff=User::where('role','STAFF')->first();$assigned=$staff->assignedEvents()->first();$otherStaff=User::where('role','STAFF')->whereKeyNot($staff->id)->first();$hidden=Event::create(['created_by'=>User::where('role','PIC')->value('id'),'event_name'=>'Private assignment','event_type'=>'Meeting','event_date'=>today()->addWeek(),'start_time'=>'16:00','end_time'=>'17:00','staff_required'=>1,'status'=>'SCHEDULED']);$hidden->staff()->sync([$otherStaff->id]);$response=$this->actingAs($staff)->getJson('/api/events')->assertOk();$this->assertContains($assigned->id,collect($response->json('data'))->pluck('id'));$this->assertNotContains($hidden->id,collect($response->json('data'))->pluck('id'));$this->actingAs($staff)->getJson("/api/events/$hidden->id")->assertForbidden();}
 public function test_staff_and_approver_cannot_access_admin_management():void{foreach(['STAFF','APPROVER'] as $role)$this->actingAs(User::where('role',$role)->first())->getJson('/api/users')->assertForbidden();}
 public function test_staff_and_venue_availability_come_from_persisted_schedule():void{$event=Event::with('staff')->where('status','SCHEDULED')->first();$response=$this->actingAs(User::where('role','PIC')->first())->getJson('/api/bootstrap?event_date='.$event->event_date->format('Y-m-d').'&start_time=10:00&end_time=11:00')->assertOk();$this->assertFalse(collect($response->json('staff'))->firstWhere('id',$event->staff->first()->id)['available']);$this->assertFalse(collect($response->json('venues'))->firstWhere('id',$event->venue_id)['available']);}
 public function test_rejection_resubmission_and_approval_persist():void{$pic=User::where('role','PIC')->first();$approver=User::where('role','APPROVER')->first();$venue=Venue::first();$event=Event::create(['created_by'=>$pic->id,'event_name'=>'Operational Review','event_type'=>'Meeting','event_date'=>today()->addDays(10),'start_time'=>'08:00','end_time'=>'09:00','venue_id'=>$venue->id,'staff_required'=>0,'status'=>'PENDING_APPROVAL']);$this->actingAs($approver)->postJson("/api/events/$event->id/decision",['decision'=>'REJECT','rejection_reason'=>'Mohon lengkapi detail kegiatan.'])->assertOk()->assertJsonPath('status','REJECTED');$this->actingAs($pic)->putJson("/api/events/$event->id",['event_name'=>'Operational Review','event_type'=>'Meeting','event_date'=>today()->addDays(10)->format('Y-m-d'),'start_time'=>'08:00','end_time'=>'09:00','venue_id'=>$venue->id,'staff_required'=>0,'description'=>'Review operasional bulanan.','staff_ids'=>[],'submit'=>true])->assertOk()->assertJsonPath('status','PENDING_APPROVAL');$this->actingAs($approver)->postJson("/api/events/$event->id/decision",['decision'=>'APPROVE'])->assertOk()->assertJsonPath('status','SCHEDULED');$this->assertDatabaseHas('approvals',['event_id'=>$event->id,'status'=>'REJECTED','rejection_reason'=>'Mohon lengkapi detail kegiatan.']);$this->assertDatabaseHas('approvals',['event_id'=>$event->id,'status'=>'APPROVED']);}
 public function test_revise_and_resubmit_updates_same_event_and_enforces_ownership():void{$pic=User::where('role','PIC')->first();$approver=User::where('role','APPROVER')->first();$otherPic=User::create(['name'=>'Unrelated PIC','email'=>'other-pic@technolife.test','password'=>'password','role'=>'PIC','is_active'=>true]);$venue=Venue::first();$event=Event::create(['created_by'=>$pic->id,'event_name'=>'Pernikahan','event_type'=>'External Event','event_date'=>today()->addDays(11),'start_time'=>'13:20','end_time'=>'14:30','venue_id'=>$venue->id,'participants_count'=>100,'staff_required'=>0,'status'=>'PENDING_APPROVAL']);$originalId=$event->id;$this->actingAs($approver)->postJson("/api/events/$originalId/decision",['decision'=>'REJECT','rejection_reason'=>'Tambahkan deskripsi kegiatan.'])->assertOk();$countBefore=Event::count();$payload=['event_name'=>'Pernikahan','event_type'=>'External Event','event_date'=>today()->addDays(11)->format('Y-m-d'),'start_time'=>'13:20','end_time'=>'14:30','venue_id'=>$venue->id,'participants_count'=>100,'staff_required'=>0,'staff_ids'=>[],'description'=>'Deskripsi revisi yang diminta approver.','submit'=>true];$this->actingAs($otherPic)->putJson("/api/events/$originalId",$payload)->assertForbidden();$response=$this->actingAs($pic)->putJson("/api/events/$originalId",$payload)->assertOk()->assertJsonPath('id',$originalId)->assertJsonPath('status','PENDING_APPROVAL')->assertJsonPath('description','Deskripsi revisi yang diminta approver.');$this->assertSame($countBefore,Event::count());$this->assertSame($originalId,$event->fresh()->id);$this->assertDatabaseHas('approvals',['event_id'=>$originalId,'status'=>'REJECTED','rejection_reason'=>'Tambahkan deskripsi kegiatan.']);$this->assertDatabaseHas('approvals',['event_id'=>$originalId,'status'=>'RESUBMITTED','approver_id'=>$pic->id]);}
 public function test_assignment_creates_database_notification_for_staff():void{$pic=User::where('role','PIC')->first();$staff=User::where('role','STAFF')->first();$venue=Venue::first();$response=$this->actingAs($pic)->postJson('/api/events',['event_name'=>'Staff Briefing','event_type'=>'Meeting','event_date'=>today()->addDays(12)->format('Y-m-d'),'start_time'=>'13:00','end_time'=>'14:00','venue_id'=>$venue->id,'staff_required'=>1,'staff_ids'=>[$staff->id],'submit'=>true])->assertCreated();$this->assertDatabaseHas('notifications',['user_id'=>$staff->id,'event_id'=>$response->json('id'),'title'=>'Penugasan event']);}
 public function test_staff_workspace_endpoints_are_role_and_ownership_scoped():void{$staff=User::where('email','staff1@technolife.test')->first();$other=User::where('email','staff6@technolife.test')->first();$assigned=$staff->assignedEvents()->first();$hidden=Event::create(['created_by'=>User::where('role','PIC')->value('id'),'event_name'=>'Other staff only','event_type'=>'Meeting','event_date'=>today()->addDays(8),'start_time'=>'10:00','end_time'=>'11:00','staff_required'=>1,'status'=>'SCHEDULED']);$hidden->staff()->sync([$other->id]);$dashboard=$this->actingAs($staff)->getJson('/api/staff/dashboard')->assertOk()->assertJsonStructure(['stats'=>['assigned','today','upcoming','completed'],'schedule','notifications']);$assignments=$this->actingAs($staff)->getJson('/api/staff/assignments')->assertOk();$this->assertContains($assigned->id,collect($assignments->json('data'))->pluck('id'));$this->assertNotContains($hidden->id,collect($assignments->json('data'))->pluck('id'));$this->actingAs($staff)->getJson("/api/staff/assignments/$hidden->id")->assertForbidden();$this->actingAs(User::where('role','PIC')->first())->getJson('/api/staff/dashboard')->assertForbidden();}
 public function test_seeded_staff_accounts_keep_expected_ids_names_and_roles():void{$expected=[4=>'Alya Putri',5=>'Dimas Saputra',6=>'Fajar Ramadhan',7=>'Maya Lestari',8=>'Rizky Maulana',9=>'Sinta Dewi'];foreach($expected as $id=>$name){$this->assertDatabaseHas('users',['id'=>$id,'name'=>$name,'email'=>'staff'.($id-3).'@technolife.test','role'=>'STAFF']);}}
 public function test_authenticated_shell_notifications_return_pagination_and_unread_count():void{$user=User::where('role','APPROVER')->first();$this->actingAs($user)->getJson('/api/notifications')->assertOk()->assertJsonStructure(['data','current_page','unread_count']);}
}
